# Generated by Django 5.2 on 2026-08-02 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('room_type', models.CharField(default='live', max_length=30)),
                ('status', models.CharField(default='scheduled', max_length=30)),
                ('max_participants', models.IntegerField(default=50)),
                ('is_private', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('recording_enabled', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True)),
                ('agora_channel', models.CharField(blank=True, max_length=150)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_host', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_participations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='live.liveroom')),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
    ]
