# Generated by Django 5.2 on 2026-08-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('range_name', models.CharField(default='Semana', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('engagement', models.PositiveIntegerField(default=0)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_metrics', to='social.socialaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('posts_count', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('profile_views', models.IntegerField(default=0)),
                ('website_clicks', models.IntegerField(default=0)),
                ('avg_likes_7d', models.FloatField(default=0)),
                ('avg_comments_7d', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='social.socialaccount')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('account', 'date')},
            },
        ),
    ]
