# Generated by Django 5.2 on 2026-08-02 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReplyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('applies_to', models.CharField(default='dm', max_length=30)),
                ('trigger_type', models.CharField(default='keyword', max_length=30)),
                ('trigger_keywords', models.TextField(blank=True)),
                ('reply_mode', models.CharField(default='fixed', max_length=30)),
                ('fixed_reply', models.TextField(blank=True)),
                ('ai_instructions', models.TextField(blank=True)),
                ('ai_tone', models.CharField(blank=True, max_length=30)),
                ('max_per_hour', models.IntegerField(default=0)),
                ('max_per_day', models.IntegerField(default=0)),
                ('active_hours_start', models.IntegerField(default=0)),
                ('active_hours_end', models.IntegerField(default=23)),
                ('is_active', models.BooleanField(default=True)),
                ('reply_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reply_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_message_id', models.CharField(max_length=150, unique=True)),
                ('message_type', models.CharField(default='dm', max_length=30)),
                ('sender_platform_id', models.CharField(blank=True, max_length=150)),
                ('sender_username', models.CharField(blank=True, max_length=100)),
                ('sender_display_name', models.CharField(blank=True, max_length=150)),
                ('sender_avatar_url', models.URLField(blank=True)),
                ('content', models.TextField()),
                ('media_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('auto_replied', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_messages', to='social.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InboxReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('replied_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='inbox.inboxmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
